/**
 * Turns src/design/tokens.ts into CSS custom properties and W3C DTCG JSON.
 * Pure functions so the test suite can check the committed files are current.
 */
import {
  border,
  category,
  desktopTypeQuery,
  duration,
  easing,
  fluidRange,
  fontFamily,
  glow,
  glowSpec,
  grid,
  layout,
  motionDistance,
  motionScale,
  palette,
  radius,
  semantic,
  shadow,
  size,
  space,
  stagger,
  typeScale,
  zIndex,
  type PaletteName,
  type TypeStep,
} from "./tokens.ts";

const HEADER = "Generated by `npm run tokens` from src/design/tokens.ts. Do not edit by hand.";

const round = (n: number, places = 4) => Number(n.toFixed(places));
const rem = (px: number) => `${round(px / 16)}rem`;

function isPaletteName(value: string): value is PaletteName {
  return Object.hasOwn(palette, value);
}

/** Font size that scales linearly from the mobile frame to the desktop frame, clamped at both ends. */
export function fluidSize(mobilePx: number, desktopPx: number): string {
  if (mobilePx === desktopPx) return rem(mobilePx);
  const slope = (desktopPx - mobilePx) / (fluidRange.max - fluidRange.min);
  const intercept = mobilePx - slope * fluidRange.min;
  return `clamp(${rem(mobilePx)}, ${rem(intercept)} + ${round(slope * 100)}vw, ${rem(desktopPx)})`;
}

function colorVar(value: string): string {
  return isPaletteName(value) ? `var(--palette-${value})` : value;
}

/* -------------------------------------------------------------------------- */
/* CSS                                                                        */
/* -------------------------------------------------------------------------- */

export function toCss(): string {
  const root: string[] = [];
  const section = (title: string) => root.push(``, `  /* ${title} */`);
  const decl = (name: string, value: string | number) => root.push(`  --${name}: ${value};`);

  section("color.palette");
  for (const [name, entry] of Object.entries(palette)) decl(`palette-${name}`, entry.value);

  section("color.semantic");
  for (const [group, values] of Object.entries(semantic)) {
    for (const [name, value] of Object.entries(values)) decl(`color-${group}-${name}`, colorVar(value));
  }

  section("color.category");
  for (const [name, { bg, fg }] of Object.entries(category)) {
    decl(`category-${name}-bg`, colorVar(bg));
    decl(`category-${name}-fg`, colorVar(fg));
  }

  section("color.glow");
  for (const [name, value] of Object.entries(glow)) decl(`glow-${name}`, value);
  for (const [name, value] of Object.entries(glowSpec)) decl(`glow-${name}`, value);

  section("font");
  for (const [name, value] of Object.entries(fontFamily)) decl(`font-family-${name}`, value);

  section("type");
  for (const [name, step] of Object.entries(typeScale) as [string, TypeStep][]) {
    decl(`type-${name}-family`, `var(--font-family-${step.family})`);
    decl(`type-${name}-size`, fluidSize(step.mobile.size, step.desktop.size));
    decl(`type-${name}-leading`, step.mobile.leading);
    decl(`type-${name}-weight`, step.weight);
    decl(`type-${name}-tracking`, step.tracking);
  }

  section("space");
  for (const [name, px] of Object.entries(space)) decl(`space-${name}`, `${px}px`);

  section("radius");
  for (const [name, { value }] of Object.entries(radius)) decl(`radius-${name}`, `${value}px`);

  section("size");
  for (const [name, value] of Object.entries(size)) {
    decl(`size-${name}`, name === "icon-stroke" ? value : `${value}px`);
  }

  section("border");
  for (const [name, value] of Object.entries(border)) decl(`border-${name}`, value);

  section("shadow");
  for (const [name, { value }] of Object.entries(shadow)) decl(`shadow-${name}`, value);

  section("layout");
  for (const [name, { value }] of Object.entries(layout)) decl(`layout-${name}`, `${value}px`);
  decl("grid-columns", grid.mobile.columns);
  decl("grid-margin", `${grid.mobile.margin}px`);
  decl("grid-gutter", `${grid.mobile.gutter}px`);

  section("z-index");
  for (const [name, value] of Object.entries(zIndex)) decl(`z-${name}`, value);

  section("motion");
  for (const [name, { value }] of Object.entries(duration)) decl(`motion-duration-${name}`, `${value}ms`);
  for (const [name, { value }] of Object.entries(stagger)) decl(`motion-stagger-${name}`, `${value}ms`);
  for (const [name, { value }] of Object.entries(easing)) decl(`motion-easing-${name}`, value);
  for (const [name, { value }] of Object.entries(motionDistance)) decl(`motion-distance-${name}`, value);
  for (const [name, { value }] of Object.entries(motionScale)) decl(`motion-scale-${name}`, value);

  const blocks: string[] = [`/* ${HEADER} */`, ``, `:root {${root.join("\n")}\n}`];

  const media = (query: string, lines: string[]) =>
    blocks.push(``, `@media ${query} {`, `  :root {`, ...lines.map((l) => `    ${l}`), `  }`, `}`);

  for (const step of Object.values(grid)) {
    if (!step.query) continue;
    media(step.query, [
      `--grid-columns: ${step.columns};`,
      `--grid-margin: ${step.margin}px;`,
      `--grid-gutter: ${step.gutter}px;`,
    ]);
  }

  media(
    desktopTypeQuery,
    (Object.entries(typeScale) as [string, TypeStep][])
      .filter(([, step]) => step.desktop.leading !== step.mobile.leading)
      .map(([name, step]) => `--type-${name}-leading: ${step.desktop.leading};`),
  );

  const reducedMotion = [
    ...Object.entries(duration).map(([name, { reduced }]) => `--motion-duration-${name}: ${reduced}ms;`),
    ...Object.entries(stagger).map(([name, { reduced }]) => `--motion-stagger-${name}: ${reduced}ms;`),
    ...Object.entries(motionDistance).map(([name, { reduced }]) => `--motion-distance-${name}: ${reduced};`),
    ...Object.entries(motionScale).map(([name, { reduced }]) => `--motion-scale-${name}: ${reduced};`),
  ];
  media("(prefers-reduced-motion: reduce)", reducedMotion);
  blocks.push(
    ``,
    `/* Same overrides on demand, e.g. a reduced-motion preview or an in-app setting. */`,
    `[data-motion="reduced"] {`,
    ...reducedMotion.map((l) => `  ${l}`),
    `}`,
  );

  blocks.push(``, `/* Type styles: one class per step in the type scale. */`);
  for (const [name, step] of Object.entries(typeScale) as [string, TypeStep][]) {
    blocks.push(
      ``,
      `.type-${name} {`,
      `  font-family: var(--type-${name}-family);`,
      `  font-size: var(--type-${name}-size);`,
      `  line-height: var(--type-${name}-leading);`,
      `  font-weight: var(--type-${name}-weight);`,
      `  letter-spacing: var(--type-${name}-tracking);`,
      ...(step.transform ? [`  text-transform: ${step.transform};`] : []),
      `}`,
    );
  }

  return blocks.join("\n") + "\n";
}

/* -------------------------------------------------------------------------- */
/* DTCG JSON (Figma Variables / Tokens Studio)                                */
/* -------------------------------------------------------------------------- */

type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

/** rgba(r, g, b, a) -> #RRGGBBAA, because DTCG colour values are hex. */
function toHex(value: string): string {
  const m = /^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/.exec(value);
  if (!m) return value;
  const hex = (n: number) => n.toString(16).padStart(2, "0").toUpperCase();
  return `#${hex(+m[1])}${hex(+m[2])}${hex(+m[3])}${hex(Math.round(+m[4] * 255))}`;
}

function colorToken(value: string, description?: string): Json {
  const token: Record<string, Json> = {
    $type: "color",
    $value: isPaletteName(value) ? `{color.palette.${value}}` : toHex(value),
  };
  if (description) token.$description = description;
  return token;
}

const dimension = (px: number, description?: string): Json =>
  description ? { $type: "dimension", $value: `${px}px`, $description: description } : { $type: "dimension", $value: `${px}px` };

const FAMILY_NAMES = { display: "Plus Jakarta Sans", ui: "Inter" } as const;

export function toDtcg(): Json {
  const mapValues = <T>(obj: Record<string, T>, fn: (value: T, key: string) => Json): { [key: string]: Json } =>
    Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, fn(v, k)]));

  const typography = mapValues(typeScale as Record<string, TypeStep>, (step) => {
    const variant = (frame: TypeStep["desktop"]): Json => ({
      $type: "typography",
      $value: {
        fontFamily: FAMILY_NAMES[step.family],
        fontSize: `${frame.size}px`,
        fontWeight: step.weight,
        lineHeight: frame.leading,
        letterSpacing: step.tracking,
      },
    });
    return { $description: step.usage, desktop: variant(step.desktop), mobile: variant(step.mobile) };
  });

  const shadowToken = (value: string, description: string): Json => {
    const m = /^(-?\d+)(?:px)? (-?\d+)(?:px)? (\d+)px (rgba\([^)]+\))$/.exec(value);
    if (!m) return { $description: description, $type: "shadow", $value: [] };
    return {
      $type: "shadow",
      $description: description,
      $value: { offsetX: `${m[1]}px`, offsetY: `${m[2]}px`, blur: `${m[3]}px`, spread: "0px", color: toHex(m[4]) },
    };
  };

  return {
    $description: HEADER,
    color: {
      palette: mapValues(palette, (entry) => ({
        $type: "color",
        $value: entry.value,
        $description: `${entry.role}. ${entry.guidance}`,
        $extensions: { "com.dfx.source": entry.source },
      })),
      semantic: mapValues(semantic, (group) => mapValues(group, (value: string) => colorToken(value))),
      category: mapValues(category, ({ bg, fg }) => ({ bg: colorToken(bg), fg: colorToken(fg) })),
      glow: mapValues(glow, (value: string) => colorToken(value)),
    },
    typography,
    space: mapValues(space, (px: number) => dimension(px)),
    radius: mapValues(radius, ({ value, usage }) => dimension(value, usage)),
    size: mapValues(size, (value: number, key) =>
      key === "icon-stroke" ? { $type: "number", $value: value } : dimension(value),
    ),
    shadow: Object.fromEntries(
      Object.entries(shadow)
        .filter(([, { value }]) => value !== "none")
        .map(([name, { value, usage }]) => [name, shadowToken(value, usage)]),
    ),
    layout: mapValues(layout, ({ value, usage }) => dimension(value, usage)),
    motion: {
      duration: mapValues(duration, ({ value, reduced, usage }) => ({
        $type: "duration",
        $value: `${value}ms`,
        $description: `${usage}. Reduced motion: ${reduced}ms.`,
      })),
      easing: mapValues(easing, ({ value, usage }) => ({
        $type: "cubicBezier",
        $value: (value.match(/-?[\d.]+/g) ?? []).map(Number),
        $description: usage,
      })),
    },
  };
}

export function toDtcgString(): string {
  return JSON.stringify(toDtcg(), null, 2) + "\n";
}

/** Files written by `npm run tokens`, relative to the repo root. */
export function generatedFiles(): { path: string; content: string }[] {
  return [
    { path: "src/styles/tokens.css", content: toCss() },
    { path: "public/tokens/dfx.tokens.json", content: toDtcgString() },
  ];
}
